## Haiku Generic Build Makefile ##
NAME = poulsbo.accelerant
TYPE = SHARED

SRCS = ../src/accelerant.c
LOCAL_INCLUDE_PATHS = ../src
LIBS = be

## Include the Makefile-Engine that ships with the Haiku SDK.
include /boot/system/develop/etc/makefile-engine
