## Haiku Generic Build Makefile ##
NAME = poulsbo
TYPE = DRIVER

SRCS = ../src/driver.c
LOCAL_INCLUDE_PATHS = ../src

DRIVER_PATH = graphics

## Include the Makefile-Engine that ships with the Haiku SDK.
include /boot/system/develop/etc/makefile-engine
